// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLd0tIOP1SjHS6rSDaKqm_GZiNjluNHfo',
    appId: '1:138449858748:web:f473e26642f61d3dde20b9',
    messagingSenderId: '138449858748',
    projectId: 'note1-app-2adba',
    authDomain: 'note1-app-2adba.firebaseapp.com',
    storageBucket: 'note1-app-2adba.firebasestorage.app',
    measurementId: 'G-VC9HJ08ZR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC6aHCSq0XkyFUqihnmtG2klFHDGEBz8A',
    appId: '1:138449858748:android:a08b9a944a088343de20b9',
    messagingSenderId: '138449858748',
    projectId: 'note1-app-2adba',
    storageBucket: 'note1-app-2adba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmupK-6cT9o16KHgqxn6pUD6kLPIJaZsk',
    appId: '1:138449858748:ios:a3f5c1770f162951de20b9',
    messagingSenderId: '138449858748',
    projectId: 'note1-app-2adba',
    storageBucket: 'note1-app-2adba.firebasestorage.app',
    iosBundleId: 'com.example.note1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmupK-6cT9o16KHgqxn6pUD6kLPIJaZsk',
    appId: '1:138449858748:ios:a3f5c1770f162951de20b9',
    messagingSenderId: '138449858748',
    projectId: 'note1-app-2adba',
    storageBucket: 'note1-app-2adba.firebasestorage.app',
    iosBundleId: 'com.example.note1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLd0tIOP1SjHS6rSDaKqm_GZiNjluNHfo',
    appId: '1:138449858748:web:b94dd87a672a7ebbde20b9',
    messagingSenderId: '138449858748',
    projectId: 'note1-app-2adba',
    authDomain: 'note1-app-2adba.firebaseapp.com',
    storageBucket: 'note1-app-2adba.firebasestorage.app',
    measurementId: 'G-TDCY9SDJNP',
  );
}
